services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=springbootdb'
      - 'POSTGRES_PASSWORD=postgres@123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
